/*******************************************************************************
 *
 * This file is part of libcommute, a C++11/14/17 header-only library allowing
 * to manipulate polynomial expressions with quantum-mechanical operators.
 *
 * Copyright (C) 2016-2019 Igor Krivenko <igor.s.krivenko@gmail.com>
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 ******************************************************************************/

#include "catch2/catch.hpp"

#include "./gamma.hpp"

#include <libcommute/algebra_tags.hpp>
#include <libcommute/expression/expression.hpp>
#include <libcommute/qoperator/basis_space.hpp>
#include <libcommute/qoperator/qoperator.hpp>

#include <algorithm>
#include <array>
#include <complex>
#include <memory>
#include <vector>

std::complex<double> I(0,1);

namespace libcommute {

//
// 4-dimensional basis space generated by gamma matrices
//

class basis_space_gamma : public basis_space<int> {

  using base = basis_space<int>;

public:

  // Value symantics
  basis_space_gamma() : base(0) {}
  basis_space_gamma(basis_space_gamma const&) = default;
  basis_space_gamma(basis_space_gamma&&) noexcept = default;
  basis_space_gamma& operator=(basis_space_gamma const&) = default;
  basis_space_gamma& operator=(basis_space_gamma&&) noexcept = default;

  virtual std::unique_ptr<base> clone() const override {
    return make_unique<basis_space_gamma>(*this);
  }

  virtual int algebra_id() const override { return gamma_::algebra_id(); }
  virtual int n_bits() const override { return 2; }
};

//
// Action of a gamma-matrix monomial
//

template<> class monomial_action<gamma_> {

  std::vector<int> index_sequence;

public:

  monomial_action(detail::monomial_range_t<int> const& m_range,
                  hilbert_space<int> const& hs) {
    for(auto it = m_range.first; it != m_range.second; ++it)
      index_sequence.push_back(std::get<0>(it->indices()));
    std::reverse(index_sequence.begin(), index_sequence.end());
  }

  inline bool act(sv_index_type in_index,
                  sv_index_type & out_index,
                  std::complex<double> & coeff) const {
    out_index = in_index;
    for(int index : index_sequence) {
      switch(index) {
        case 0:
          coeff *= std::array<double, 4>{1,1,-1,-1}[out_index];
          break;
        case 1:
          coeff *= std::array<double, 4>{-1,-1,1,1}[out_index];
          out_index = std::array<sv_index_type,4>{3,2,1,0}[out_index];
          break;
        case 2:
          coeff *= std::array<std::complex<double>, 4>{-I,I,I,-I}[out_index];
          out_index = std::array<sv_index_type,4>{3,2,1,0}[out_index];
          break;
        case 3:
          coeff *= std::array<std::complex<double>, 4>{-1,1,1,-1}[out_index];
          out_index = std::array<sv_index_type,4>{2,3,0,1}[out_index];
          break;
      }
    }
    return true;
  }
};

} // namespace libcommute

using namespace libcommute;

template<typename ExprType>
void check_qoperator(ExprType const& expr1, ExprType const& expr2) {
  hilbert_space<int> hs{basis_space_gamma()};
  auto qop1 = qoperator<std::complex<double>, gamma_>(expr1, hs);
  auto qop2 = qoperator<std::complex<double>, gamma_>(expr2, hs);

  std::vector<std::complex<double>> in(4), out1(4), out2(4);

  for(sv_index_type in_index : {0,1,2,3}) {
    in[in_index] = 1;
    CHECK(qop1(in) == qop2(in));
    CHECK(qop1 * in == qop2 * in);
    qop1(in, out1);
    qop2(in, out2);
    CHECK(out1 == out2);
    in[in_index] = 0;
  }
}

TEST_CASE("qoperator for expressions with gamma-matrices",
          "[qoperator_gamma]") {
  using mon_type = monomial<int>;
  using expr_type = expression<std::complex<double>, int>;

  // Metric
  auto eta = [](int mu, int nu) -> double {
    return (mu == nu) * (mu == 0 ? 1 : -1);
  };

  std::vector<expr_type> Gamma; // Gamma matrices
  std::vector<expr_type> Gammac; // Covariant Gamma matrices
  for(int mu : {0, 1, 2, 3}) {
    Gamma.emplace_back(expr_type(1.0, mon_type(generator_gamma(mu))));
    Gammac.emplace_back(expr_type(eta(mu, mu),
                                  mon_type(generator_gamma(mu))));
  }

  SECTION("Commutation relations") {
    for(int mu = 0; mu < 4; ++mu) {
      for(int nu = 0; nu < 4; ++nu) {
        auto lhs = Gamma[mu] * Gamma[nu] + Gamma[nu] * Gamma[mu];
        auto rhs = expr_type(2 * eta(mu, nu));
        check_qoperator(lhs, rhs);
      }
    }
  }

  SECTION("Hermitian conjugate") {
    check_qoperator(conj(Gamma[0]), Gamma[0]);
    for(int k = 1; k < 4; ++k) {
      check_qoperator(conj(Gamma[k]), -Gamma[k]);
    }
    for(int mu = 0; mu < 4; ++mu) {
      check_qoperator(conj(Gamma[mu]), Gamma[0] * Gamma[mu] * Gamma[0]);
    }
  }

  auto Gamma5 = I * Gamma[0] * Gamma[1] * Gamma[2] * Gamma[3];

  SECTION("Gamma^5") {
    for(int mu = 0; mu < 4; ++mu) {
      check_qoperator(Gamma5 * Gamma[mu] + Gamma[mu] * Gamma5, expr_type());
    }
    check_qoperator(Gamma5 * Gamma5, expr_type(1));
    check_qoperator(conj(Gamma5), Gamma5);
  }

  //
  // https://en.wikipedia.org/wiki/Gamma_matrices#Miscellaneous_identities
  //

  SECTION("Identity 1") {
    expr_type s;
    for(int mu = 0; mu < 4; ++mu)
      s += Gamma[mu] * Gammac[mu];
    check_qoperator(s, expr_type(4));
  }

  SECTION("Identity 2") {
    for(int nu = 0; nu < 4; ++nu) {
      expr_type s;
      for(int mu = 0; mu < 4; ++mu)
        s += Gamma[mu] * Gamma[nu] * Gammac[mu];
      check_qoperator(s, -2.0*Gamma[nu]);
    }
  }

  SECTION("Identity 3") {
    for(int nu = 0; nu < 4; ++nu) {
      for(int rho = 0; rho < 4; ++rho) {
        expr_type s;
        for(int mu = 0; mu < 4; ++mu)
          s += Gamma[mu] * Gamma[nu] * Gamma[rho] * Gammac[mu];
        check_qoperator(s, expr_type(4*eta(nu, rho)));
      }
    }
  }

  SECTION("Identity 4") {
    for(int nu = 0; nu < 4; ++nu) {
      for(int rho = 0; rho < 4; ++rho) {
        for(int sigma = 0; sigma < 4; ++sigma) {
          expr_type s;
          for(int mu = 0; mu < 4; ++mu)
            s += Gamma[mu] * Gamma[nu] * Gamma[rho] * Gamma[sigma] * Gammac[mu];
          check_qoperator(s, -2.0 * Gamma[sigma] * Gamma[rho] * Gamma[nu]);
        }
      }
    }
  }

  // 4D Levi-Civita symbol
  auto eps = [](int i1, int i2, int i3, int i4) -> double {
    return (i4 - i3)*(i4 - i2)*(i4 - i1)*(i3 - i2)*(i3 - i1)*(i2 - i1)/12;
  };

  SECTION("Identity 5") {
    for(int mu = 0; mu < 4; ++mu) {
      for(int nu = 0; nu < 4; ++nu) {
        for(int rho = 0; rho < 4; ++rho) {
          auto lhs = Gamma[mu] * Gamma[nu] * Gamma[rho];
          auto rhs = eta(mu, nu) * Gamma[rho] +
                     eta(nu, rho) * Gamma[mu] -
                     eta(mu, rho) * Gamma[nu];
          for(int sigma = 0; sigma < 4; ++sigma) {
            rhs += -I*eps(sigma, mu, nu, rho) * Gammac[sigma] * Gamma5;
          }
          check_qoperator(lhs, rhs);
        }
      }
    }
  }
}
